version: '3.9'

services:
  nginx: 
    container_name: nginx
    build: ./nginx
    depends_on:
      - nextjs
      - laravel
      - php
    volumes:
      - ./laravel/:/var/www/
    ports:
      - 9095:80
    networks:
      - backend

  nextjs: 
    container_name: nextjs
    build: ./nextjs
    expose:
      - 3000
    networks:
      - backend

  laravel:
    container_name: laravel
    image: nginx:latest
    ports:
      - 9096:4000
    expose:
      - 9096
    volumes:
      - ./nginx/backend.nginx:/etc/nginx/conf.d/default.conf
      - ./laravel/:/var/www/
    depends_on:
      - php
    links:
     - php
    networks:
      - backend

  php:
    container_name: php
    build:
      context: ./laravel
    volumes:
      - ./laravel/:/var/www/
    networks:
      - backend

  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - 9097:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: JaZIJLpYRk
      MYSQL_USER: fGOYopjPAo
      MYSQL_ROOT_PASSWORD: QWFcaIMKpb
      MYSQL_PASSWORD: QWFcaIMKpb
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data: