version: '3.9'

services:
  nginx: 
    container_name: apl_nginx
    build: ./nginx
    depends_on:
      - nextjs
      - laravel
      - php
      - mysql
    volumes:
      - ./laravel/:/var/www/
    ports:
      - 9095:80
    networks:
      - backend

  nextjs:
    container_name: apl_nextjs
    build: ./nextjs
    expose:
      - 3000
    networks:
      - backend

  laravel:
    container_name: apl_laravel
    image: nginx:latest
    ports:
      - 9096:4000
    expose:
      - 9096
    volumes:
      - ./nginx/backend.nginx:/etc/nginx/conf.d/default.conf
      - ./laravel/:/var/www/
    depends_on:
      - php
      - mysql
    links:
     - php
     - mysql
    networks:
      - backend

  php:
    container_name: apl_php
    build:
      context: ./laravel
    volumes:
      - ./laravel/:/var/www/
    networks:
      - backend

  mysql:
    container_name: apl_mysql
    image: mysql:8
    ports:
      - 9097:3306
    expose:
      - 9097
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: GYgkjVGk
      MYSQL_USER: txlgnZnZ
      MYSQL_ROOT_PASSWORD: dIRYAKWe
      MYSQL_PASSWORD: dIRYAKWe
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data: